name: "Apollo Windows Defender Survey"
description: "Enumerate the status of Defender an various EDRs"
trigger: manual
run_as: self

steps:
  - name: "defender base"
    description: "List defender base key"
    depends_on: []
    inputs:
      CALLBACK_ID: env.display_id
    action: task_create
    continue_on_error: true
    action_data:
      callback_display_id: CALLBACK_ID
      command_name: reg_query
      params_dictionary:
        Hive: "HKLM"
        Key: "Software\\Microsoft\\Windows Defender"

  - name: "real-time protection"
    description: "List real-time protection status"
    depends_on: 
      - "defender base"
    inputs:
      CALLBACK_ID: env.display_id
    action: task_create
    continue_on_error: true
    action_data:
      callback_display_id: CALLBACK_ID
      command_name: reg_query
      params_dictionary:
        Hive: "HKLM"
        Key: "Software\\Microsoft\\Windows Defender\\Real-Time Protection"

  - name: "features"
    description: "List defender features"
    depends_on: 
      - "real-time protection"
    inputs:
      CALLBACK_ID: env.display_id
    action: task_create
    continue_on_error: true
    action_data:
      callback_display_id: CALLBACK_ID
      command_name: reg_query
      params_dictionary:
        Hive: "HKLM"
        Key: "Software\\Microsoft\\Windows Defender\\Features"

  - name: "spynet"
    description: "List spynet status"
    depends_on: 
      - "features"
    inputs:
      CALLBACK_ID: env.display_id
    action: task_create
    continue_on_error: true
    action_data:
      callback_display_id: CALLBACK_ID
      command_name: reg_query
      params_dictionary:
        Hive: "HKLM"
        Key: "Software\\Microsoft\\Windows Defender\\SpyNet"

  - name: "protected folder"
    description: "List protected folders"
    depends_on: 
      - "spynet"
    inputs:
      CALLBACK_ID: env.display_id
    action: task_create
    continue_on_error: true
    action_data:
      callback_display_id: CALLBACK_ID
      command_name: reg_query
      params_dictionary:
        Hive: "HKLM"
        Key: "Software\\Microsoft\\Windows Defender\\Windows Defender Exploit Guard\\Controlled Folder Access\\ProtectedFolders"

  - name: "dlp rules"
    description: "List DLP rules"
    depends_on: 
      - "protected folder"
    inputs:
      CALLBACK_ID: env.display_id
    action: task_create
    continue_on_error: true
    action_data:
      callback_display_id: CALLBACK_ID
      command_name: reg_query
      params_dictionary:
        Hive: "HKLM"
        Key: "Software\\Microsoft\\Windows Defender\\Windows Defender Exploit Guard\\DLP\\Rules"

  - name: "exclusion paths"
    description: "List exclusion paths"
    depends_on: 
      - "dlp rules"
    inputs:
      CALLBACK_ID: env.display_id
    action: task_create
    continue_on_error: true
    action_data:
      callback_display_id: CALLBACK_ID
      command_name: reg_query
      params_dictionary:
        Hive: "HKLM"
        Key: "Software\\Microsoft\\Windows Defender\\exclusions\\paths"


###########################################################
# Seatbelt
###########################################################

  - name: "register forge_net_Seatbelt"
    depends_on:
      - "exclusion paths"
    inputs:
      CALLBACK_ID: env.display_id
    action: task_create
    action_data:
      callback_display_id: CALLBACK_ID
      command_name: forge_register
      payload_type: forge
      params_dictionary:
        collectionName: SharpCollection
        commandName: Seatbelt
        remove: false

  - name: "forge_net_Seatbelt defensive_controls"
    description: "Seatbelt defensive controls"
    depends_on:
      - "register forge_net_Seatbelt"
    inputs:
      CALLBACK_ID: env.display_id
    action: task_create
    action_data:
      callback_display_id: CALLBACK_ID
      command_name: forge_net_Seatbelt
      payload_type: forge
      params_dictionary:
        args: "WindowsDefender AntiVirus AMSIProviders Sysmon WindowsEventForwarding WindowsFirewall AppLocker AuditPolicies AuditPolicyRegistry PowerShell McAfeeConfigs McAfeeSiteList SecurityPackages"
        version: 4.7_Any
        execution: inline_assembly

###########################################################
# SharpEDRChecker
###########################################################

  - name: "register forge_net_SharpEDRChecker"
    depends_on:
      - "forge_net_Seatbelt defensive_controls"
    inputs:
      CALLBACK_ID: env.display_id
    action: task_create
    action_data:
      callback_display_id: CALLBACK_ID
      command_name: forge_register
      payload_type: forge
      params_dictionary:
        collectionName: SharpCollection
        commandName: SharpEDRChecker
        remove: false

  - name: "execute forge_net_SharpEDRChecker"
    description: "run forge_net_SharpEDRChecker to look for AV"
    depends_on:
      - "register forge_net_SharpEDRChecker"
    inputs:
      CALLBACK_ID: env.display_id
    action: task_create
    action_data:
      callback_display_id: CALLBACK_ID
      command_name: forge_net_SharpEDRChecker
      payload_type: forge
      params_dictionary:
        args: ""
        version: 4.7_Any
        execution: inline_assembly


